version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  api:
    build: .
    environment:
      - PORT=${PORT}
      - DB_URI=postgres://${DB_USER}:${DB_PWD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - NODE_ENV=prod
    depends_on:
      - db
    ports:
      - "3000:3000"
